// Restoran ma'lumotlar bazasi (Taomlar, Ichimliklar, Sharhlar)
const RESTAURANT_DATA = {
    info: {
        name: "DEWAYS",
        tagline: "Grand Restaurant & Lounge",
        slogan: "Sharqona mehmondo'stlik va Yevropa nafisligi uyg'unligi",
        phone: "+998 93 097 18 80",
        phoneSecondary: "+998 93 097 18 80",
        address: "Toshkent shahri, Mirobod tumani, Amir Temur shox ko'chasi, 48-uy",
        workingHours: "Dushanba - Yakshanba: 10:00 - 23:30",
        instagram: "@deways.restaurant",
        telegram: "https://t.me/deways_restaurant"
    },
    categories: [
        { id: "all", name: "Barcha taomlar", icon: "fa-utensils" },
        { id: "national", name: "Milliy taomlar", icon: "fa-bowl-rice" },
        { id: "steaks", name: "Steyk va Gril", icon: "fa-fire-burner" },
        { id: "salads", name: "Salat va Gazaklar", icon: "fa-leaf" },
        { id: "soups", name: "Sho'rvalar", icon: "fa-mug-hot" },
        { id: "desserts", name: "Shirinliklar", icon: "fa-cake-candles" },
        { id: "drinks", name: "Ichimlik va Kokteyllar", icon: "fa-wine-glass" }
    ],
    dishes: [
        {
            id: 1,
            name: "Deways Maxsus To'y Oshi",
            category: "national",
            price: 78000,
            oldPrice: 85000,
            rating: 5.0,
            reviewsCount: 142,
            weight: "450 gr",
            calories: "720 kkal",
            badge: "Xit taom",
            badgeColor: "gold",
            isHalal: true,
            isSpicy: false,
            description: "Devzira guruch, sara lahm qo'zi go'shti, sarg'ish sabzi, qazi va bedana tuxumlari bilan tayyorlangan mualliflik to'y oshi.",
            ingredients: "Devzira guruch, lahm qo'zi go'shti, qazi, dumba yog'i, zira, mayiz, no'xat, bedana tuxumi",
            image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80"
        },
        {
            id: 2,
            name: "Vagyu Ribay Steyki (Prime)",
            category: "steaks",
            price: 245000,
            oldPrice: null,
            rating: 4.9,
            reviewsCount: 89,
            weight: "350 gr",
            calories: "680 kkal",
            badge: "Chef's Choice",
            badgeColor: "red",
            isHalal: true,
            isSpicy: false,
            description: "Josper pechida o'tin olovida pishirilgan mramor mol go'shti, rozmarinli sariyog' va trufel sousi bilan.",
            ingredients: "Mramor mol go'shti (Ribeye), yangi rozmarin, dengiz tuzi, qalampir, sarimsoq, trufel moyi",
            image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80"
        },
        {
            id: 3,
            name: "Tandir Qo'zichoq Qovurg'asi",
            category: "national",
            price: 135000,
            oldPrice: 150000,
            rating: 4.9,
            reviewsCount: 110,
            weight: "400 gr",
            calories: "790 kkal",
            badge: "Eng ko'p buyurtma",
            badgeColor: "gold",
            isHalal: true,
            isSpicy: false,
            description: "Maxsus marinadlangan yosh qo'zichoq qovurg'alari tandirda 3 soat davomida past olovda yumshoq pishirilgan.",
            ingredients: "Yosh qo'zi go'shti, tog' ziravorlari, xushbo'y piyoz, limon, yalpiz",
            image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80"
        },
        {
            id: 4,
            name: "Lazzat Qozon Kabob",
            category: "national",
            price: 98000,
            oldPrice: null,
            rating: 4.8,
            reviewsCount: 95,
            weight: "420 gr",
            calories: "820 kkal",
            badge: "An'anaviy",
            badgeColor: "blue",
            isHalal: true,
            isSpicy: false,
            description: "Qizarib qovurilgan yosh buzoqcha go'shti va qasmoqli qizil kartoshka, tillarang piyoz bilan.",
            ingredients: "Buzoq go'shti, yosh kartoshka, dumba, zira, kashnich urug'i, ko'katlar",
            image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80"
        },
        {
            id: 5,
            name: "Klassik Shashlik Assorti (6 xil)",
            category: "steaks",
            price: 185000,
            oldPrice: 210000,
            rating: 5.0,
            reviewsCount: 204,
            weight: "650 gr",
            calories: "980 kkal",
            badge: "Katta tovoq",
            badgeColor: "green",
            isHalal: true,
            isSpicy: true,
            description: "Qo'y go'shti, qiyma lula, tovuq filesi, jigar, qo'zi qovurg'asi va sabzavotli sixlar to'plami.",
            ingredients: "Qo'y lahm, tovuq go'shti, qo'zi jigar, qiyma, dumba, pomidor, achchiq qalampir",
            image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=800&q=80"
        },
        {
            id: 6,
            name: "Burrata va Yangi Pomidorlar Salati",
            category: "salads",
            price: 68000,
            oldPrice: null,
            rating: 4.7,
            reviewsCount: 52,
            weight: "260 gr",
            calories: "340 kkal",
            badge: "Yengil",
            badgeColor: "green",
            isHalal: true,
            isSpicy: false,
            description: "Nafis italyancha Burrata pishlog'i, Shirin pomidorlar, rayhon barglari va Pesto sousi.",
            ingredients: "Burrata pishlog'i, cherry pomidor, yangi rayhon, Pesto sousi, zaytun moyi, balzamik krem",
            image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80"
        },
        {
            id: 7,
            name: "Qirollik Sezar Salati (Krevetka bilan)",
            category: "salads",
            price: 75000,
            oldPrice: 85000,
            rating: 4.8,
            reviewsCount: 88,
            weight: "280 gr",
            calories: "410 kkal",
            badge: "Klassika",
            badgeColor: "blue",
            isHalal: true,
            isSpicy: false,
            description: "Grilda qovurilgan yo'lbars krevetkalari, Aysberg barglari, parmezan va maxsus an'anaviy Sezar sousi.",
            ingredients: "Yo'lbars krevetkalari, aysberg, kroutonlar, Parmezan pishlog'i, klassik sezar sousi",
            image: "https://images.unsplash.com/photo-1550304943-4f24f54ddde9?auto=format&fit=crop&w=800&q=80"
        },
        {
            id: 8,
            name: "Tom Yam Dengiz Mahsulotlari Sho'rvasi",
            category: "soups",
            price: 85000,
            oldPrice: null,
            rating: 4.9,
            reviewsCount: 67,
            weight: "380 gr",
            calories: "320 kkal",
            badge: "Achchiq",
            badgeColor: "red",
            isHalal: true,
            isSpicy: true,
            description: "Krevetkalar, midiyalar, kalamar, kokos suti va xushbo'y tay o'tlari bilan tayyorlangan afsonaviy o'tkir sho'rva.",
            ingredients: "Krevetka, kalamar, midiya, shiitake qo'ziqorinlari, limon o'ti, galangal, kokos suti, yasmin guruchi",
            image: "https://images.unsplash.com/photo-1548943487-a2e4e43b4853?auto=format&fit=crop&w=800&q=80"
        },
        {
            id: 9,
            name: "Tandir Somsa (Vagyu go'shti bilan)",
            category: "national",
            price: 24000,
            oldPrice: null,
            rating: 5.0,
            reviewsCount: 310,
            weight: "160 gr",
            calories: "380 kkal",
            badge: "Qarsildoq",
            badgeColor: "gold",
            isHalal: true,
            isSpicy: false,
            description: "Qat-qat qarsildoq xamir ichida mayin buzoqcha go'shti va piyoz. Tandirda pishirilgan.",
            ingredients: "Qatlama xamir, maydalangan lahm go'sht, piyoz, sedana, zira, tabiiy sariyog'",
            image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=800&q=80"
        },
        {
            id: 10,
            name: "San-Sebastian Trufel Pishlog'i Torti",
            category: "desserts",
            price: 52000,
            oldPrice: 60000,
            rating: 5.0,
            reviewsCount: 175,
            weight: "180 gr",
            calories: "450 kkal",
            badge: "Top Desert",
            badgeColor: "gold",
            isHalal: true,
            isSpicy: false,
            description: "Ispancha kuydirilgan chizkeyk, ustidan oqib turuvchi iliq Belgiya shokoladli ganash bilan tortiladi.",
            ingredients: "Philadelphia kremli pishloq, qaymoq, vanil, Belgiya qora va sutli shokoladi",
            image: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=800&q=80"
        },
        {
            id: 11,
            name: "Deways Mualliflik Paxlavasi",
            category: "desserts",
            price: 45000,
            oldPrice: null,
            rating: 4.9,
            reviewsCount: 92,
            weight: "150 gr",
            calories: "510 kkal",
            badge: "Sharqona",
            badgeColor: "gold",
            isHalal: true,
            isSpicy: false,
            description: "Eron za'faroni, tog' asali va sara pista mag'izlari bilan tayyorlangan nozik qatlama paxlava, qaymoq bilan.",
            ingredients: "Yupqa qatlama xamir, pista, yong'oq, za'faron siropi, tog' asali, qaymoq",
            image: "https://images.unsplash.com/photo-1519869325930-281384150729?auto=format&fit=crop&w=800&q=80"
        },
        {
            id: 12,
            name: "Deways Oltin Limonad (Mualliflik)",
            category: "drinks",
            price: 36000,
            oldPrice: null,
            rating: 4.9,
            reviewsCount: 130,
            weight: "450 ml",
            calories: "120 kkal",
            badge: "Yangi",
            badgeColor: "blue",
            isHalal: true,
            isSpicy: false,
            description: "Yangi siqilgan sitrus mevalar, tabiiy za'faron damlamasi, yalpiz va qulupnayli sovuq kokteyl.",
            ingredients: "Apelsin, laym, yangi yalpiz, tabiiy za'faron ekstrakti, gazlangan tog' suvi, muz",
            image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80"
        }
    ],
    reviews: [
        {
            id: 1,
            author: "Azamat Shokirov",
            role: "Doimiy mehmon",
            avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80",
            rating: 5,
            date: "2 kun oldin",
            text: "Deways restoranida oilaviy bayram o'tkazdik. To'y oshi va Vagyu ribay steyki mutlaqo ajoyib! Servis Michelin darajasida, xodimlar nihoyatda xushmuomala. Toshkentdagi eng sevimli maskanimizga aylandi."
        },
        {
            id: 2,
            author: "Malika Karimova",
            role: "Food blogger",
            avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80",
            rating: 5,
            date: "1 hafta oldin",
            text: "San-Sebastian chizkeyki va mualliflik Deways oltin limonadi shunchaki lazzat portlashi! Interyer dizayni juda zamonaviy, fotosessiyalar uchun ajoyib burchaklar ko'p. 10/10 tavsiya qilaman!"
        },
        {
            id: 3,
            author: "Jamshidbek Rustamov",
            role: "Tadbirkor",
            avatar: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=150&q=80",
            rating: 5,
            date: "2 hafta oldin",
            text: "VIP xonani biznes uchrashuv uchun band qilgandik. Atmosfera tinch, akustika va jonli skripka musiqasi oqshomimizni unutilmas qildi. Yetkazib berish xizmati ham tezkor va taomlar issiq keldi."
        }
    ],
    chefs: [
        {
            name: "Shavkat Aliyev",
            role: "Bosh oshpaz (Brand Chef)",
            exp: "18 yillik xalqaro tajriba",
            desc: "Dubay va Istanbulning 5 yulduzli mehmonxona restoranlarida ishlagan mahoratli usta.",
            image: "https://images.unsplash.com/photo-1577219491135-ce391730fb2c?auto=format&fit=crop&w=600&q=80"
        },
        {
            name: "Umar Xasanov",
            role: "Go'sht va Josper bo'yicha usta",
            exp: "12 yillik tajriba",
            desc: "Haqiqiy o'tin olovida steyklar va shashlik tayyorlash bo'yicha yetakchi mutaxassis.",
            image: "https://images.unsplash.com/photo-1581299894007-aaa50297cf16?auto=format&fit=crop&w=600&q=80"
        },
        {
            name: "Gulbahor Mirzayeva",
            role: "Bosh qandolatchi (Pastry Chef)",
            exp: "9 yillik tajriba",
            desc: "Fransuz va sharqona shirinliklar bo'yicha ko'plab xalqaro tanlovlar g'olibi.",
            image: "https://images.unsplash.com/photo-1607631568010-a87245c0daf8?auto=format&fit=crop&w=600&q=80"
        }
    ]
};
